# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: senstemp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='senstemp.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0esenstemp.proto\"!\n\nSensorTemp\x12\x13\n\x0btemperatura\x18\x01 \x02(\x02'
)




_SENSORTEMP = _descriptor.Descriptor(
  name='SensorTemp',
  full_name='SensorTemp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperatura', full_name='SensorTemp.temperatura', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=51,
)

DESCRIPTOR.message_types_by_name['SensorTemp'] = _SENSORTEMP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorTemp = _reflection.GeneratedProtocolMessageType('SensorTemp', (_message.Message,), {
  'DESCRIPTOR' : _SENSORTEMP,
  '__module__' : 'senstemp_pb2'
  # @@protoc_insertion_point(class_scope:SensorTemp)
  })
_sym_db.RegisterMessage(SensorTemp)


# @@protoc_insertion_point(module_scope)
